#配置使用那个文件
#dev为开发环境 prod为部署环境
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8
    username: root
    password: 1108
  spring:
    profiles:
      active: dev

    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        servlet:
            content-type: text/html
        enabled: true
        encoding: utf-8
        mode: HTML
        check-template-location: true


